### ISSUE TITLE
After upgrading to 1.5.0 version backward compatibility is gone

### ISSUE THREAD

**Issue by hejkerooo** [clowdhaus/argo-cd-action#10]
**Describe the bug**
We were using `clowdhaus/argo-cd-action/@main` for GHA but today our pipelines started to fail - we use node
They work fine for `v1.4.2` version but we are using nodejs in version 12.

**Expected behavior**
Should be backward compatible/breaking changes should be annoucned. 

**Additional context**
NodeJS 12 & 14

**Comment by bryantbiggs** [comment]
apologies for this @hejkerooo - the change is backwards compatible since users are not affected by the underlying change of node12 runner runtime to node16. however, the issue is in the manner in which GitHub rolls out these changes - it appears their fleet of runners are not all in sync which is causing issues
- https://github.com/clowdhaus/argo-cd-action/commit/9231f64f5d6f09abea249712323a91afd760c5dd#comments
- https://github.com/actions/runner/pull/1439#issuecomment-983958249

hopefully the runner fleet will become in sync soon and this issue will be resolved

**Comment by hejkerooo** [comment]
@bryantbiggs 
Thank you for your explanation,

I will close the issue in that case
Thanks once again
